name: API Test Framework
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '57 18 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Execute Test
      run: |
            mkdir -p logs
            mvn clean test -Dsuite=suite -X | tee logs/maven.log
            
      working-directory: Restassured/
    - name: Upload a Build Artifact
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: demorestlogs
        path: Restassured/logs

    - name: Publish Test Report
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: TestNG Results
        path: Restassured/target/surefire-reports/junitreports/TEST-*.xml
        reporter: java-junit

        
          
        
      
    

      
